#!/usr/bin/with-contenv bash

## THIS FILE IS REWRITTEN EVERY TIME THE CONTAINER STARTS
## CUSTOMIZATIONS WILL BE LOST

. /config/.donoteditthisfile.conf

if [ ! "$ORIGVALIDATION" = "dns" ] && [ ! "$ORIGVALIDATION" = "duckdns" ]; then
    if ps aux | grep [n]ginx: > /dev/null; then
        s6-svc -d /var/run/s6/services/nginx
    fi
fi
